### ISSUE TITLE
 [bot] Implent 

### ISSUE THREAD

**Issue by TheSpaceArmy** [ExoZoneDev/BeepBot-Feedback#7]
Art should implent a !seed if people want to suggest a seed they could do !seed the name of seed and when u die it could tell u whos next that would be cool

**Comment by TheSpaceGuild** [comment]
or like Make a Mod that intergrates with beepbot and when for example mindless dies and hes out of the world the bot choose's for him .

**Comment by UnwrittenFun** [comment]
This is currently out of the scope of the project.
